services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # 루트 사용자 비밀번호
      MYSQL_DATABASE: ${MYSQL_DATABASE} # 초기화할 데이터베이스 이름
      MYSQL_USER: ${MYSQL_USER} # 추가 사용자
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} # 추가 사용자의 비밀번호
    ports:
      - "3306:3306" # 호스트의 포트 3306을 컨테이너의 3306 포트로 매핑
    volumes:
      - ./db/data:/var/lib/mysql # 데이터베이스 데이터를 호스트에 저장하는 볼륨
    networks:
      - db_network

volumes:
  db_data:
    driver: local
    driver_opts:
      type: bind
      device: ./db # 로컬의 실제 경로로 수정해야 합니다
      o: bind

networks:
  db_network:
    driver: bridge
