services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - moheng-network

volumes:
  db-data:
    driver: local
    driver_opts:
      type: bind
      device: ./source
      o: bind

networks:
  moheng-network:
    name: moheng-network
    driver: bridge
    # 네트워크 이름을 명시하지 않으면 디렉토리 접두사가 붙어서 생성됨
